title: Trabajos de Jardineria los Weros
email: info@pacificsunrealestate.com.mx
phone1: +1-551-817-1918
phone2: +1-551-817-1918
schedule: Lun - Vie 10:00 - 18:00  /  Sabado 10:00 - 14:00
address:  Nicol√°s Romero
description: Todo lo relacionado a la construccion decoracion mantenimiento de jardines, fumigaciones , abonos, muros verticales, sistemas de riego.
baseurl: "" 
url: "https://pacificsunrealestate.com.mx" 
google_analytics: 
lang: es-mx

social:
  name: Trabajos de Jardineria los Weros
  links:
facebook_username: https://www.facebook.com/edithernandezsolorio
instagram_username:  https://www.facebook.com/edithernandezsolorio
youtube_username: https://www.facebook.com/edithernandezsolorio

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag  
  - jekyll-sitemap

twitter:
  username: Jardineria los Weros
  card: summary
  
collections:
  agentes:
    output: true
  casasenventa:
    output: true
  casasenrenta:
    output: true
    
exclude:
  - HTML-MASTER/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

defaults:
  -
    scope:
      path: ""
    values:
      lang: "es-mx"
      lazy: true
      image: 
        path: /trabajosdejarniderialosweros/favicon/og-image.jpg
        height: 279
        width: 279
      author: Jardineria los Weros 